### PR TITLE
MNT: Re-rendered with conda-smithy 2.3.0

### LINKED ISSUE #9: python 3.6 is not supported

### PR DESCRIPTION
**Pull request by isuruf**
Also fix windows skips

Fixes #9

### CODE REVIEW

**Comment by asmeurer** [comment]
Why is it skipped on Windows? Shouldn't the build have failed without those skips?

**Comment by isuruf** [comment]
I don't understand what you are saying here. For windows, only python 3.5 and 3.6 are available since the dependencies need MSVC 2015 or above.

**Comment by asmeurer** [comment]
So why didn't the build fail in the other rerender PR?

**Comment by isuruf** [comment]
because the skip was `win and not py35` and py36 was skipped. now it is `win and py<35` and both py35 and py36 are built.

**Comment by asmeurer** [comment]
Ah gotcha.

**Pull request merged**
